### ISSUE TITLE
VS 2017

### ISSUE THREAD

**Issue by 7Kronos** [VirtoCommerce/vc-visualstudio-templates#1]
Hi guys,

What a coincidence, was forking the repo to make the extension VS 15.x complaint when I saw a dev branch and @artem-dudarev already working on it today.

@artem-dudarev can you just change the versions range to 14.0,15.**2** ?

> Release Date: April 20, 2017 - version 15.2
> Release Date: June 26, 2017 - version 15.3

I just tested 15.2 works just fine.

**Comment by artem-dudarev** [comment]
Changed version ranges from [14.0,15.0) to [14.0,15.0] in source.extension.vsixmanifest.
Is that what you wanted?

**Comment by 7Kronos** [comment]
Yes @artem-dudarev, this is the change I made and it works !
