### ISSUE TITLE
Actualize the template on marketplace

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-visualstudio-templates#3]
the last commit here is from year 2017! Is this the latest existing version? 
What's the best way to use it: marketplace.visualstudio.com or something else?

**Comment by eMazeika** [comment]
v2.0.0 released. @artem-dudarev, can you update it in marketplace?

**Comment by OlegoO** [comment]
https://marketplace.visualstudio.com/items?itemName=Virto-Commerce.VirtoCommerceModuleTemplates
